version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.8.0
  jq: circleci/jq@dev:alpha

executors:
  ci-base:
    resource_class: small
    docker:
      - image: cibuilds/base

  machine:
    machine: true

  macos:
    macos:
      xcode: "10.2.0"

  docker:
    resource_class: small
    docker:
      - image: node

jobs:
  install:
    parameters:
      executor:
        type: executor
      version:
        type: string
        default: latest

    executor: <<parameters.executor>>
    steps:
      - jq/install:
          version: <<parameters.version>>

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [
    install-latest-alpine-master,
    install-latest-machine-master,
    install-latest-macos-master,
    install-latest-docker-master,
    install-older-alpine-master,
    install-older-machine-master,
    install-older-macos-master,
    install-older-docker-master
  ]

add-ssh-keys: &add-ssh-keys
  [add_ssh_keys: {fingerprints: ["0c:0f:b7:32:1f:7e:55:1b:f9:e9:ba:93:f9:4f:e1:e3"]}]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: circleci/jq
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-workflow:
          context: orb-publishing
          name: trigger-integration-dev
          ssh-fingerprints: 0c:0f:b7:32:1f:7e:55:1b:f9:e9:ba:93:f9:4f:e1:e3
          cleanup-tags: true
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          ssh-fingerprints: 0c:0f:b7:32:1f:7e:55:1b:f9:e9:ba:93:f9:4f:e1:e3
          cleanup-tags: true
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration_tests-prod_deploy:
    jobs:
      # triggered by non-master branch commits
      # latest jq
      - install:
          name: install-latest-alpine-dev
          executor: ci-base
          context: orb-publishing
          filters: *integration-dev_filters
          pre-steps:
            - run: apk add gnupg

      - install:
          name: install-latest-machine-dev
          executor: machine
          context: orb-publishing
          filters: *integration-dev_filters
          pre-steps:
            - run: sudo rm -rf /usr/bin/jq

      - install:
          name: install-latest-macos-dev
          executor: macos
          context: orb-publishing
          filters: *integration-dev_filters

      - install:
          name: install-latest-docker-dev
          executor: docker
          context: orb-publishing
          filters: *integration-dev_filters

      # older jq
      - install:
          name: install-older-alpine-dev
          executor: ci-base
          version: jq-1.5
          context: orb-publishing
          filters: *integration-dev_filters
          pre-steps:
            - run: apk add gnupg

      - install:
          name: install-older-machine-dev
          executor: machine
          version: jq-1.4
          context: orb-publishing
          filters: *integration-dev_filters
          pre-steps:
            - run: sudo rm -rf /usr/bin/jq

      - install:
          name: install-older-macos-dev
          executor: macos
          version: jq-1.3
          context: orb-publishing
          filters: *integration-dev_filters

      - install:
          name: install-older-docker-dev
          executor: docker
          version: jq-1.2
          context: orb-publishing
          filters: *integration-dev_filters

      # triggered by master branch commits
      # latest
      - install:
          name: install-latest-alpine-master
          executor: ci-base
          context: orb-publishing
          filters: *integration-master_filters
          pre-steps:
            - run: apk add gnupg

      - install:
          name: install-latest-machine-master
          executor: machine
          context: orb-publishing
          filters: *integration-master_filters

      - install:
          name: install-latest-macos-master
          executor: macos
          context: orb-publishing
          filters: *integration-master_filters

      - install:
          name: install-latest-docker-master
          executor: docker
          context: orb-publishing
          filters: *integration-master_filters

      # older jq
      - install:
          name: install-older-alpine-master
          executor: ci-base
          version: jq-1.5
          context: orb-publishing
          filters: *integration-master_filters
          pre-steps:
            - run: apk add gnupg

      - install:
          name: install-older-machine-master
          executor: machine
          version: jq-1.4
          context: orb-publishing
          filters: *integration-master_filters

      - install:
          name: install-older-macos-master
          executor: macos
          version: jq-1.3
          context: orb-publishing
          filters: *integration-master_filters

      - install:
          name: install-older-docker-master
          executor: docker
          version: jq-1.2
          context: orb-publishing
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: circleci/jq
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          release: minor
          context: orb-publishing
          orb-name: circleci/jq
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          release: major
          context: orb-publishing
          orb-name: circleci/jq
          orb-ref: dev:alpha
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
