version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.8.0
  jq: circleci/jq@dev:alpha

executors:
  ci-base:
    resource_class: small
    docker:
      - image: cibuilds/base

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [

  ]

add-ssh-keys: &add-ssh-keys
  [add_ssh_keys: {fingerprints: ["40:21:b7:d7:fe:ea:dd:80:ca:c8:34:7a:37:b4:b4:d2"]}]

# not in use yet—add this functionality to git-tools-orb when it's ready
# cleanup-git-tag: &cleanup-git-tag
#   [run: {when: "always", name: "cleanup tag", command: "git config --global user.email $CIRCLE_USERNAME@users.noreply.github.com && git config --global user.name $CIRCLE_USERNAME && git push --delete origin $CIRCLE_TAG"}]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: circleci/slack
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-workflow:
          context: orb-publishing
          name: trigger-integration-dev
          ssh-fingerprints: 79:ae:f5:10:17:8a:d2:9a:ed:63:5c:b0:92:66:23:49
          cleanup-tags: true
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          ssh-fingerprints: 79:ae:f5:10:17:8a:d2:9a:ed:63:5c:b0:92:66:23:49
          cleanup-tags: true
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration_tests-prod_deploy:
    jobs:
      # triggered by non-master branch commits
      - notifytest:
          name: notifytest-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - statustestpass-full:
          name: statustestpass-full-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - statustestpass-minimal:
          name: statustestpass-minimal-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - approvaltest:
          name: approvaltest-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - approvaltest-mention-here:
          name: approvaltest-mention-here-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - approvaltest-mention-here-2:
          name: approvaltest-mention-here-2-dev
          context: orb-publishing
          filters: *integration-dev_filters

      - slack/approval-notification:
          name: approval-notification-job-dev
          context: orb-publishing
          mentions: "${ORBS_USER_GROUP_UUID}"
          filters: *integration-dev_filters

      # triggered by master branch commits
      - notifytest:
          name: notifytest-master
          context: orb-publishing
          filters: *integration-master_filters

      - statustestpass-full:
          name: statustestpass-full-master
          context: orb-publishing
          filters: *integration-master_filters

      - statustestpass-minimal:
          name: statustestpass-minimal-master
          context: orb-publishing
          filters: *integration-master_filters

      - approvaltest:
          name: approvaltest-master
          context: orb-publishing
          filters: *integration-master_filters

      - approvaltest-mention-here:
          name: approvaltest-mention-here-master
          context: orb-publishing
          filters: *integration-master_filters

      - approvaltest-mention-here-2:
          name: approvaltest-mention-here-2-master
          context: orb-publishing
          filters: *integration-master_filters

      - slack/approval-notification:
          name: approval-notification-job-master
          context: orb-publishing
          mentions: "${ORBS_USER_GROUP_UUID}"
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: circleci/slack
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          release: minor
          context: orb-publishing
          orb-name: circleci/slack
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          release: major
          context: orb-publishing
          orb-name: circleci/slack
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
