version: 2.1

orbs:
  build-tools: circleci/build-tools@2.5.0
  orb-tools: circleci/orb-tools@10.0.5
  jq: circleci/jq@<<pipeline.parameters.dev-orb-version>>

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

executors:
  macos:
    macos:
      xcode: 12.5.1
  node:
    docker:
      - image: cimg/node:lts
  base:
    docker:
      - image: cimg/base:stable
  openjdk:
    docker:
      - image: cimg/openjdk:16.0.2
  machine:
    machine:
      image: ubuntu-2004:202107-02

jobs:
  install:
    parameters:
      executor:
        type: executor
      version:
        type: string
        default: latest

    executor: <<parameters.executor>>
    steps:
      - build-tools/install-ci-tools

      - jq/install:
          version: <<parameters.version>>

orb_prep_jobs: &orb_prep_jobs
  [
    orb-tools/lint,
    orb-tools/pack
  ]

prod-deploy_requires: &prod-deploy_requires
  [
    install-latest-base,
    install-latest-machine,
    install-latest-macos,
    install-latest-docker,
    install-latest-openjdk,
    install-older-base,
  ]

workflows:
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint

      - orb-tools/pack

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: circleci/jq
          requires: *orb_prep_jobs

      - orb-tools/trigger-integration-tests-workflow:
          context: orb-publishing
          requires: [orb-tools/publish-dev]

  integration_tests-prod_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # latest
      - install:
          name: install-latest-base
          executor: base
          context: orb-publishing
          # Test that files are not left behind
          post-steps:
            - checkout

      - install:
          name: install-latest-machine
          executor: machine
          context: orb-publishing
          # Test that files are not left behind
          post-steps:
            - checkout

      - install:
          name: install-latest-macos
          executor: macos
          context: orb-publishing
          # Test that files are not left behind
          post-steps:
            - checkout

      - install:
          name: install-latest-docker
          executor: node
          context: orb-publishing
          # Test that files are not left behind
          post-steps:
            - checkout

      - install:
          name: install-latest-openjdk
          executor: openjdk
          context: orb-publishing
          # Test that files are not left behind
          post-steps:
            - checkout

      # older jq
      - install:
          name: install-older-base
          executor: base
          version: jq-1.5
          context: orb-publishing
          # Test that files are not left behind
          post-steps:
            - checkout

      - orb-tools/dev-promote-prod-from-commit-subject:
          ssh-fingerprints: 0c:0f:b7:32:1f:7e:55:1b:f9:e9:ba:93:f9:4f:e1:e3
          context: orb-publisher
          orb-name: circleci/jq
          add-pr-comment: true
          bot-token-variable: GHI_TOKEN
          bot-user: orb-publisher
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          requires: *prod-deploy_requires
          filters:
            branches:
              only: master
